name: Deploy to sekailabo.com

on:
  push:
    branches:
      - main  # mainブランチにpushしたとき自動デプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: SSH経由でシンレンタルサーバーにデプロイ
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: sv3084.wpx.ne.jp
          username: wpxe852659
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 10022
          script: |
            cd ${{ secrets.THEME_PATH }}
            git pull origin main
